### ISSUE TITLE
Поиск изображений до 22.05-23.05

### ISSUE THREAD

**Issue by kruglovaliza** [kruglovaliza/TRPO_lab_7#1]
Найти изображения всех твёрдых элементов(не включая 10 строчку)
На прикреплённой картинке металлы отмечены голубым цветом
![image](https://user-images.githubusercontent.com/61828720/82449209-89cda280-9ab3-11ea-9326-d09ff5bb8692.png)

**Comment by Mildonir** [comment]
![Рубидий](https://user-images.githubusercontent.com/61844936/82534279-9272b700-9b4d-11ea-9acd-64b741c97e7c.jpg)
![Скадий](https://user-images.githubusercontent.com/61844936/82534283-93a3e400-9b4d-11ea-8ad4-35858a24f496.jpg)
![Стронций](https://user-images.githubusercontent.com/61844936/82534285-93a3e400-9b4d-11ea-8abf-a403476f4a9e.jpg)
![Таллий](https://user-images.githubusercontent.com/61844936/82534286-943c7a80-9b4d-11ea-9a6b-236f60674bd8.jpg)
![Франций](https://user-images.githubusercontent.com/61844936/82534287-943c7a80-9b4d-11ea-8274-faa0b0cc31ff.jpg)
![Цезий](https://user-images.githubusercontent.com/61844936/82534288-94d51100-9b4d-11ea-984a-0add067a645f.jpg)
![Алюминий](https://user-images.githubusercontent.com/61844936/82534290-94d51100-9b4d-11ea-97bd-29442676b51a.jpg)
![Барий](https://user-images.githubusercontent.com/61844936/82534292-956da780-9b4d-11ea-810e-7ba252cc8cc6.jpg)
![Индий](https://user-images.githubusercontent.com/61844936/82534293-956da780-9b4d-11ea-9fea-07484182fef4.jpg)
![Иттрий](https://user-images.githubusercontent.com/61844936/82534294-96063e00-9b4d-11ea-9b2c-f3b061637fbc.jpg)
![Калий](https://user-images.githubusercontent.com/61844936/82534295-96063e00-9b4d-11ea-921a-59fc053e2cd6.jpg)
![Кальций](https://user-images.githubusercontent.com/61844936/82534296-969ed480-9b4d-11ea-87ac-9bc3509ca0f2.jpg)
![Лантан](https://user-images.githubusercontent.com/61844936/82534299-969ed480-9b4d-11ea-980c-9baf1581fbf2.jpg)
![Литий](https://user-images.githubusercontent.com/61844936/82534300-97376b00-9b4d-11ea-91de-350478fa32f8.jpg)
![Магний](https://user-images.githubusercontent.com/61844936/82534301-97376b00-9b4d-11ea-8d40-89d42c141293.jpg)
![Натрий](https://user-images.githubusercontent.com/61844936/82534303-97d00180-9b4d-11ea-8600-da987e966291.jpg)
![Радий](https://user-images.githubusercontent.com/61844936/82534314-9bfc1f00-9b4d-11ea-912e-8a4d2f7c9f17.jpg)
