### ISSUE TITLE
Заполнение табеля

### ISSUE THREAD

**Issue by kruglovaliza** [kruglovaliza/TRPO_lab_7#18]
Заполнить информацию о себе и о своих задачах

**Comment by Mildonir** [comment]
[Табель.docx](https://github.com/kruglovaliza/TRPO_lab_7/files/4711778/default.docx)

**Comment by AminaKlykova** [comment]
https://drive.google.com/file/d/1ZQlALy4ofIhfnQOEw_u79LJEawhbSBHD/view?usp=sharing
